// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_2.Models;

namespace Project_2.Migrations
{
    [DbContext(typeof(AppointmentContext))]
    [Migration("20220324063903_Reset")]
    partial class Reset
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23");

            modelBuilder.Entity("Project_2.Models.Appointment", b =>
                {
                    b.Property<long>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("SizeOfGroup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeslotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppointmentId");

                    b.HasIndex("TimeslotId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Project_2.Models.Timeslot", b =>
                {
                    b.Property<int>("TimeslotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Available")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("TimeslotId");

                    b.ToTable("Timeslots");

                    b.HasData(
                        new
                        {
                            TimeslotId = 1,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 20, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 2,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 20, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 3,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 20, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 4,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 20, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 5,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 20, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 6,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 20, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 7,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 20, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 8,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 20, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 9,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 20, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 10,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 20, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 11,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 20, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 12,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 20, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 13,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 20, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 14,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 21, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 15,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 21, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 16,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 21, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 17,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 21, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 18,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 21, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 19,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 21, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 20,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 21, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 21,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 21, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 22,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 21, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 23,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 21, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 24,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 21, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 25,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 21, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 26,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 21, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 27,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 22, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 28,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 22, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 29,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 22, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 30,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 22, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 31,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 22, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 32,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 22, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 33,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 22, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 34,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 22, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 35,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 22, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 36,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 22, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 37,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 22, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 38,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 22, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 39,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 22, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 40,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 23, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 41,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 23, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 42,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 23, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 43,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 23, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 44,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 23, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 45,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 23, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 46,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 23, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 47,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 23, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 48,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 23, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 49,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 23, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 50,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 23, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 51,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 23, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 52,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 23, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 53,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 24, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 54,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 24, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 55,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 24, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 56,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 24, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 57,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 24, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 58,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 59,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 24, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 60,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 24, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 61,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 24, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 62,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 24, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 63,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 24, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 64,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 24, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 65,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 24, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 66,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 25, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 67,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 25, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 68,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 25, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 69,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 25, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 70,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 25, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 71,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 25, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 72,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 25, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 73,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 25, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 74,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 25, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 75,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 25, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 76,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 25, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 77,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 25, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 78,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 25, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 79,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 26, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 80,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 26, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 81,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 26, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 82,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 26, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 83,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 26, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 84,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 26, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 85,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 26, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 86,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 26, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 87,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 26, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 88,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 26, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 89,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 26, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 90,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 26, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 91,
                            Available = true,
                            DateTime = new DateTime(2022, 3, 26, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Project_2.Models.Appointment", b =>
                {
                    b.HasOne("Project_2.Models.Timeslot", "Timeslot")
                        .WithMany()
                        .HasForeignKey("TimeslotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
